DO NOT MERGE fix: support new minio instances
StatCan/aaw-contrib-jupyter-notebooks pull request #46
Opened 2021-12-14 18:11 UTC by jumana-s

Closes StatCan/daaas#773

2021-12-14 19:25 UTC, blairdrummond commented
@StanHatko Any chance you could look at this? I'd be interested in your feedback

2022-01-25 16:08 UTC, bryanpaget requested changes

2022-01-25 16:29 UTC, jumana-s commented on querySQL/daaas_storage_boto3.py
> +    files = os.listdir('/vault/secrets')
It's possible with the python module Glob.
I could also do `instances = [file for file in os.listdir('/vault/secrets') if not file.endswith('.json')]`

2022-01-25 16:29 UTC, jumana-s commented on self-serve-storage/python/daaas_storage.py
> +    files = os.listdir('/vault/secrets')
It's possible with the python module Glob.
I could also do `instances = [file for file in os.listdir('/vault/secrets') if not file.endswith('.json')]`

2022-01-25 17:49 UTC, bryanpaget commented on self-serve-storage/python/daaas_storage.py
> +    files = os.listdir('/vault/secrets')
According to 

https://www.reddit.com/r/learnpython/comments/5e9pwd/which_is_much_more_efficient_globglob_or_oslistdir/

performance shouldn't be significantly different between the two. I'm thinking now to just leave it as is. Sorry for having you look into it! :-)

2022-01-25 17:50 UTC, bryanpaget commented on querySQL/daaas_storage_boto3.py
> +    files = os.listdir('/vault/secrets')
I think it can be left as is, see [note](https://github.com/StatCan/aaw-contrib-jupyter-notebooks/pull/46#discussion_r791975568).

2022-01-25 17:54 UTC, jumana-s commented on self-serve-storage/python/daaas_storage.py
> +    files = os.listdir('/vault/secrets')
Np!!

2022-01-25 18:46 UTC, bryanpaget approved these changes

2022-01-25 18:46 UTC, bryanpaget approved these changes

2022-01-25 18:51 UTC, merged